### ISSUE TITLE
Making Zone 0 (ALL) group update the corresponding lights that it would affect

### ISSUE THREAD

**Issue by phatterism** [normen/homebridge-milighthub-platform#15]
I sometimes make an Alias to a group of lights (ALL) on a Device Id to allow me to do instant changes of all lights without having to make multiple staggered calls. Is there a way to implement Zone 0 or All Group that actually also sets the state of the individual lights to whatever the state of the Zone 0 or All Group is being set to? To me, this shouldn't involve sending another command, it should just entail setting the state of the lights and then somehow pushing that state to home bridge.

**Comment by normen** [comment]
No, the hub doesn't do that kind of logic. I the hub itself the single lamps count as "on" even when the main switch was turned off. Otherwise the backchannel would update the states accordingly.
