### ISSUE TITLE
Send update to HomeKit on backchannel changes

### ISSUE THREAD

**Issue by normen** [normen/homebridge-milighthub-platform#7]
If values change the proper Characteristic.updateValue(value) should be called. Afaik this can even be used to avoid getters altogether which supposedly slow down Homebridge.

**Comment by Zer0x00** [comment]
Is this also possible if there's no hub?

I can't imagine a way that replacing getters with Characteristic.updateValue(value) ending up on the client without a hub.
Or is there some caching mechanism built in to homebridge?

**Comment by normen** [comment]
Afaik HomeKit basically IS just a cache, no? :) A distributed database about your devices, their capabilities and their states. Sending signals is what the devices and hubs do. Or am I wrong?

Am 18.11.2020 11:12 schrieb Zer0x00:

**Comment by Zer0x00** [comment]
I was thinking HomeKit is more like a product consisting of multiple protocols to communicate with each device and your Home Hub as the database.

My native HomeKit devices seem also to be polling from their Hub / the devices itself.
Anyway I'll have a look at it if I have time to do so.

Would be nice if you could also have a look at it.

**Comment by normen** [comment]
It's on my list.. Wait, this IS my list 😉

NorthernMan54 is the man to talk to concerning updateValue()

Am 18.11.2020 12:14 schrieb Zer0x00:

**Comment by normen** [comment]
Concerning HomeKit.. Pretty sure it IS a distributed database and what the hubs do is manage it - which each registered device can do, too. The devices themselves should update the states when they change locally according to that logic.

You have to consider that the "device" is the homebridge _bridge_ from HomeKits point of view. Its just for "us plugins" that the world looks like somebody is managing something.

I think we should review the code based on that thought.

**Comment by normen** [comment]
Its been implemented now. No more getters, `updateValue` is sen to sync when HomeKit is in a different state.
